from .db import Database
from .queries import (
    INSERT_CURSO,
    INSERT_DISCIPLINA,
    INSERT_CURSO_DISCIPLINA,
    SELECT_CURSO_POR_CODIGO,
    SELECT_DISCIPLINA_POR_CODIGO,
    SELECT_DISCIPLINAS_POR_CURSO_PERIODO,
    SELECT_CARGA_HORARIA_TOTAL_POR_PERIODO
)

__all__ = [
    'Database',
    'INSERT_CURSO',
    'INSERT_DISCIPLINA',
    'INSERT_CURSO_DISCIPLINA',
    'SELECT_CURSO_POR_CODIGO',
    'SELECT_DISCIPLINA_POR_CODIGO',
    'SELECT_DISCIPLINAS_POR_CURSO_PERIODO',
    'SELECT_CARGA_HORARIA_TOTAL_POR_PERIODO'
] 